'use strict';

/**
 * SERVERLESS FILE BOLIER PLATE
 */
const SERVERLESS_FILE_PATH = '/sfdc/helpers/sfdc/constants/index';

const ACTION_QUERY = 'ACTION_QUERY';

const ACTION_SOBJECT_CREATE = 'ACTION_SOBJECT_CREATE';

const ACTION_SOBJECT_READ = 'ACTION_SOBJECT_READ';

const ACTION_SOBJECT_UPDATE = 'ACTION_SOBJECT_UPDATE';

const ACTION_SOBJECT_DELETE = 'ACTION_SOBJECT_DELETE';

const ACTION_SOBJECT_UPSERT = 'ACTION_SOBJECT_UPSERT';

module.exports = {
  ACTION_QUERY,
  ACTION_SOBJECT_CREATE,
  ACTION_SOBJECT_READ,
  ACTION_SOBJECT_UPDATE,
  ACTION_SOBJECT_DELETE,
  ACTION_SOBJECT_UPSERT
}